#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

find . -name ".*" -o -name "*.bash" | \
    grep -v .git$ | \
    sed 's/^.\///g' | \
    tail -n +2 | \
    xargs -I% ln -sf $DIR/% $HOME/%

ls -al ~

# http://emacsformacosx.com/emacs-builds/Emacs-2015-04-05_01-41-26-16eec6f-universal.dmg
cp emacs/* /usr/local/bin/
